export enum TransactionType {
  INCOME,
  EXPENSE,
}

export enum CategoryType {
  AUTOMOBILE,
  BANK,
  CASH,
  CHARITY,
  CHILDCARE,
  EATING,
  EDUCATION,
  ENTERTAINMENT,
  FITNESS,
  GROCERIES,
  LOAN,
  MEDICAL,
  OTHERS,
  PETS,
  RENT,
  SAVING,
  SHOPPING,
  TRANSPORT,
  TRAVEL,
  UTILITIES,
}

export const CategoryDropdown = [
  {label: 'Automobile', value: CategoryType.AUTOMOBILE},
  {label: 'Bank', value: CategoryType.BANK},
  {label: 'Cash', value: CategoryType.CASH},
  {label: 'Charity', value: CategoryType.CHARITY},
  {label: 'Childcare', value: CategoryType.CHILDCARE},
  {label: 'Eating', value: CategoryType.EATING},
  {label: 'Education', value: CategoryType.EDUCATION},
  {label: 'Entertainment', value: CategoryType.ENTERTAINMENT},
  {label: 'Fitness', value: CategoryType.FITNESS},
  {label: 'Groceries', value: CategoryType.GROCERIES},
  {label: 'Loan', value: CategoryType.LOAN},
  {label: 'Medical', value: CategoryType.MEDICAL},
  {label: 'Others', value: CategoryType.OTHERS},
  {label: 'Pets', value: CategoryType.PETS},
  {label: 'Rent', value: CategoryType.RENT},
  {label: 'Saving', value: CategoryType.SAVING},
  {label: 'Shopping', value: CategoryType.SHOPPING},
  {label: 'Transport', value: CategoryType.TRANSPORT},
  {label: 'Travel', value: CategoryType.TRAVEL},
  {label: 'Utilities', value: CategoryType.UTILITIES},
];
